from typing import Any

class ChatOllama:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def ainvoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_tools(self, *args: Any, **kwargs: Any) -> ChatOllama: ...
    def with_retry(self, *args: Any, **kwargs: Any) -> ChatOllama: ...
