from typing import Any

class ChatOpenAI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def ainvoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_tools(self, *args: Any, **kwargs: Any) -> ChatOpenAI: ...
    def with_retry(self, *args: Any, **kwargs: Any) -> ChatOpenAI: ...

class AzureChatOpenAI:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def ainvoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_tools(self, *args: Any, **kwargs: Any) -> AzureChatOpenAI: ...
    def with_retry(self, *args: Any, **kwargs: Any) -> AzureChatOpenAI: ...
