from typing import Any

END: str
START: str

class StateGraph:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_node(self, *args: Any, **kwargs: Any) -> None: ...
    def add_edge(self, *args: Any, **kwargs: Any) -> None: ...
    def add_conditional_edges(self, *args: Any, **kwargs: Any) -> None: ...
    def compile(self, *args: Any, **kwargs: Any) -> Any: ...
