from typing import Any

class AzureMLEndpointApiType:
    serverless: str

class CustomOpenAIChatContentFormatter: ...

class AzureMLChatOnlineEndpoint:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def ainvoke(self, *args: Any, **kwargs: Any) -> Any: ...
    def bind_tools(self, *args: Any, **kwargs: Any) -> AzureMLChatOnlineEndpoint: ...
    def with_retry(self, *args: Any, **kwargs: Any) -> AzureMLChatOnlineEndpoint: ...
